spring:
    datasource:
        username: root
        password: cesspenar1
        url: jdbc:mysql://localhost:3306/tvtrucker_db
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
